### PR TITLE
Widget locations were incorrect

### PR DESCRIPTION
**Pull request by jamiefdhurst**
While developing a widget, they should be in the "shared_addons" folder, otherwise they won't show up in the widget instance list. I realise it said there were three locations, but the top two were the same?

If the third location is known, obviously just change the "two" to "three".

Also, slight formatting error with the class displaying no underscores.

### CODE REVIEW

**Comment by adamfairholm** [comment]
Hey Jamie,

The location is indeed wrong, but there are still 3 places it can be:

addons/<site-ref>/widgets
addons/shared_addons/widgets
(in your module)

Can you update it to reflect the change?

Thanks!

**Comment by jamiefdhurst** [comment]
@adamfairholm: hanks for clearing that up, I've reflected this in the docs now :)

**Comment by jamiefdhurst** [comment]
Added an update I pushed for the {{ theme:css }} helper into the docs, too.

**Comment by adamfairholm** [comment]
Merged - thanks Jamie!

**Pull request merged**
