### PR TITLE
Moved Store Submission Guidelines to contributing folder

### PR DESCRIPTION
**Pull request by brignoni**
Store Submissions Guidelines was listed on the order.txt file in the `developers/contributing` folder but the actual file was in the `developers/basics` folder. I'm not sure if it was meant to be in one or the other. You can merge this if it was meant to be in the `contributing` folder.

### CODE REVIEW

**Comment by adamfairholm** [comment]
Hey Osvaldo - good catch on this - this is correct, but for some reason it has all the other commits in with your merge - can you see what the deal is and re-submit? Thanks!

**Comment by brignoni** [comment]
I did a force update. Is it ok now?

**Comment by adamfairholm** [comment]
Hmm - all the files are still there. Mind if I just move the file myself? It'll save you the time of having to figure this out!

**Comment by brignoni** [comment]
Yes, go ahead and move it. I'll fix my repo later so that this doesn't happen with future pull requests.

**Pull request closed without merging**
